version: '2'

services:
  namenode:
    image: bde2020/hadoop-namenode:1.0.0
    networks:
      - default
    container_name: namenode
    volumes:
      - /tmp/data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
      - "constraint:node==frontend"
    env_file:
      - ./hadoop.env

  #
  # FileBrowser block
  #

  hdfsfb:
    image: bde2020/hdfs-filebrowser:3.9
    container_name: hdfsfb
    networks:
      - default
    environment:
      - NAMENODE_HOST=namenode
      - "constraint:node==frontend"

  #
  # Spark configuration block
  #

  spark-master:
    image: bde2020/spark-master:2.0.0-hadoop2.7-hive
    container_name: spark-master
    networks:
      - default
    environment:
      - "constraint:node==frontend"
    env_file:
      - ./hadoop.env

networks:
  default:
    external:
      name: mynet
