version: '2'

services:
  frontend:
    image: earthquakesan/screencast-frontend:latest
    environment:
      - "VIRTUAL_HOST=integratedui.ermilov.org,namenode.ermilov.org,filebrowser.ermilov.org,spark.ermilov.org"

  namenode:
    image: bde2020/hadoop-namenode:1.0.0
    network:
      - default
    volumes:
      - /tmp/data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode1:
    image: bde2020/hadoop-datanode:1.0.0
    network:
      - default
    volumes:
      - /tmp/data/datanode1:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

  #
  # FileBrowser block
  #

  hdfsfb:
    image: bde2020/hdfs-filebrowser:3.9
    network:
      - default
    environment:
      - NAMENODE_HOST=namenode

  #
  # Spark configuration block
  #

  spark-master:
    image: bde2020/spark-master:2.0.0-hadoop2.7-hive
    network:
      - default
    environment:
      INIT_DAEMON_STEP: setup_spark
    env_file:
      - ./hadoop.env

  spark-worker:
    image: bde2020/spark-worker:2.0.0-hadoop2.7-hive
    network:
      - default
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    env_file:
      - ./hadoop.env

  integrator-ui:
    image: earthquakesan/screencast-integrator-ui:latest
    network:
      - default

networks:
  default:
    external:
      name: mynet
